# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  domain_name: local
  secret_key_base: cf21504512985dd6218fbc1340497697c30f2e73bec98443db263bdca6a5231e42a88aa7d9fdd21ea130346ba36fb63599a45dc529c280ce282c474cd6f8a03c

test:
  domain_name: example.com
  secret_key_base: ccfd8fb55b928b6773b7629b1f50f9f9c365e17acebb3bcd203b34e07f1b015e878caade1e8198d3c40295194635ed64a57267197ad9129014a695502833741a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
